# Generated by Django 5.0.2 on 2024-02-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="bio",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
